### ISSUE TITLE
something wrong when I make this program

### ISSUE THREAD

**Issue by lxj0276** [Steinstark/track#1]
when I cmake this program then make it,it shows that:

track/rrbb/detect.cpp:46:26: error: no
      matching function for call to 'findNRLT'
  list<Rect> nrlTables = findNRLT(text, rlTables); //currently only serv...
                         ^~~~~~~~
track/rrbb/nrlt_detect.hpp:8:21: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
std::list<cv::Rect> findNRLT(cv::Mat& text, std::list<cv::Rect> tables, ...

**Comment by Steinstark** [comment]
Broke the build by not pushing all local changes. Will push and fix it later tonight. Thanks for reporting the issue.

**Comment by Steinstark** [comment]
Build issue has been fixed.
